<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLS05wdy\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLS05wdy/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLS05wdy.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLS05wdy\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerLS05wdy\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'LS05wdy',
    'container.build_id' => '8f7bba79',
    'container.build_time' => 1581768888,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLS05wdy');
